---
title: "Submetering"
author: "Murilo Miranda"
date: "3/10/2020"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

```{r, warning=FALSE}
library(RMySQL)
library(tidyverse)
library(ggthemes)
library(ggridges)
library(ggExtra)
library(viridis) # colour blind friendly palette, works in B&W also
library(lubridate)
library(zoo)
```

## Obtain the data
```{r}
con <- dbConnect(MySQL(), user='deepAnalytics', password='Sqltask1234!', dbname='dataanalytics2018', host='data-analytics-2018.cbrosir2cswx.us-east-1.rds.amazonaws.com')

# list the tables contained in the dataanalytics2018 database
dbListTables(con)

# list the attributes in the yr_2006 table
dbListFields(con, "yr_2006")

# query the attributes
query_data <- paste0("SELECT Date, Time, Sub_metering_1, Sub_metering_2, Sub_metering_3 FROM")

# fetch tables from 2006 till 2010
#dfList <- lapply(paste0("yr_", 2006:2010), 
#                 function(t) 
#                   dbGetQuery(con, paste(query_data, t)))

yr_2006 <- dbGetQuery(con, paste(query_data, "yr_2006"))
yr_2007 <- dbGetQuery(con, paste(query_data, "yr_2007"))
yr_2008 <- dbGetQuery(con, paste(query_data, "yr_2008"))
yr_2009 <- dbGetQuery(con, paste(query_data, "yr_2009"))
yr_2010 <- dbGetQuery(con, paste(query_data, "yr_2010"))
rm(query_data)
```

#### Check each table
```{r}
investigateTable <- function(data_table){
  cat("Structure:\n")
  cat(str(data_table))
  cat("\nSummary:\n")
  print(summary(data_table))
  cat("\nHead:\n")
  print(head(data_table))
  cat("\nTail:\n")
  print(tail(data_table))
}

# yr_2006:yr_2010
investigateTable(yr_2006) # from 16-12 till 31-12-2006
investigateTable(yr_2007) # full year
investigateTable(yr_2008) # full year
investigateTable(yr_2009) # full year
investigateTable(yr_2010) # full year
```

We combine all tables into one, except yr_2006 table because it only has few data from 16 until 31 December.

```{r}
submeter_data <- bind_rows(yr_2007, yr_2008, yr_2009, yr_2010)
rm(yr_2006, yr_2007, yr_2008, yr_2009, yr_2010)

investigateTable(submeter_data)
```

Date and Time attributes are character data type. We convert these attributes into DateTime type, but first we combine the two attributes in one and then convert.

```{r}
#combine the two attributes and convert the data type
submeter_data <- submeter_data %>% 
  mutate(datetime = as.POSIXct(paste(Date, Time, sep = "T"), tz = "Europe/Paris")) %>% 
  select(datetime, starts_with("Sub_"))

str(submeter_data)
```

```{r}
# verify missing values
anyNA(submeter_data)
```

<!-- Now we verify if there is data which was not added into the database. For this reason, we make a vector (called *date_Time*) from `min(submeter_data$DateTime)` to ```max(submeter_data$DateTime)` by minute. After that, we merge the *submeter_data* database with *date_Time* vector. If there is any missing value, it will be imputed by interpolation. -->

<!-- ```{r} -->
<!-- date_Time <- seq(min(submeter_data$datetime), max(submeter_data$datetime), "min") -->

<!-- ## -->
<!-- submeter_data <- submeter_data %>%  -->
<!--   full_join(as.data.frame(date_Time), by = c("datetime" = "date_Time")) %>% -->
<!--   arrange(datetime) -->

<!-- submeter_data %>% ggplot(aes(datetime, Sub_metering_1)) + geom_line() -->
<!-- ``` -->

#### Yearly
```{r}
yearly <- submeter_data %>% group_by(year = year(datetime)) %>%  
  summarize(sum_sub1 = sum(Sub_metering_1), sum_sub2 = sum(Sub_metering_2), sum_sub3 = sum(Sub_metering_3)) 

yearly %>% 
  pivot_longer(-year, names_to = "Sub_metering", values_to = "Watt_hour") %>%
  ggplot(aes(year, Watt_hour/1e6, fill = Sub_metering)) +
  geom_bar(stat = "identity", position = 'dodge', colour="black") +
  labs(
    x = "", 
    y = "Watt-hour of active energy (in Million)"
  ) + 
  scale_fill_discrete(
    name = "Sub-metering", 
    labels = c("Kitchen", "Laundry", "Heater")
  )

yearly %>% 
  pivot_longer(-year, names_to = "Sub_metering", values_to = "Watt_hour") %>%
  ggplot(aes(year, Watt_hour/1e6, fill = Sub_metering)) +
  geom_bar(stat = "identity", position = 'fill', colour="black") +
  labs(
    x = "", 
    y = "Watt-hour of active energy (in Percentage)"
  ) + 
  scale_fill_discrete(
    name = "Sub-metering", 
    labels = c("Kitchen", "Laundry", "Heater")
  )
```

#### Monthy
```{r}
monthly <- submeter_data %>% group_by(month = month(datetime, label = TRUE)) %>%  
  summarize(sum_sub1 = sum(Sub_metering_1), sum_sub2 = sum(Sub_metering_2), sum_sub3 = sum(Sub_metering_3)) 

monthly %>% 
  pivot_longer(-month, names_to = "Sub_metering", values_to = "Watt_hour") %>%
  ggplot(aes(month, Watt_hour/1e6, fill = Sub_metering)) +
  geom_bar(stat = "identity", position = 'dodge', colour="black") +
  labs(
    x = "", 
    y = "Watt-hour of active energy (in Million)"
  ) + 
  scale_fill_discrete(
    name = "Sub-metering", 
    labels = c("Kitchen", "Laundry", "Heater")
  )

monthly %>% 
  pivot_longer(-month, names_to = "Sub_metering", values_to = "Watt_hour") %>%
  ggplot(aes(month, Watt_hour/1e6, fill = Sub_metering)) +
  geom_bar(stat = "identity", position = 'fill', colour="black") +
  labs(
    x = "", 
    y = "Watt-hour of active energy (in Percentage)"
  ) + 
  scale_fill_discrete(
    name = "Sub-metering", 
    labels = c("Kitchen", "Laundry", "Heater")
  )
```


#### Daily
```{r}
daily <- submeter_data %>% 
  mutate(
    year = year(datetime),
    yday = yday(datetime),
    month = month(datetime, label = TRUE)
  ) %>% 
  group_by(year, month, yday) %>%  
  summarize(sum_sub1 = sum(Sub_metering_1), sum_sub2 = sum(Sub_metering_2), sum_sub3 = sum(Sub_metering_3)) 


# Examine distribution of sum_sub by month
ggplot(daily, aes(x = sum_sub1, y = month, height = ..density..)) +
  geom_density_ridges(stat = "density") 
ggplot(daily, aes(x = sum_sub2, y = month, height = ..density..)) +
  geom_density_ridges(stat = "density")
ggplot(daily, aes(x = sum_sub3, y = month, height = ..density..)) +
  geom_density_ridges(stat = "density")

# Examine distribution of sum_sub by month and year
ggplot(daily, aes(x = sum_sub1, y = month, height = ..density..)) +
  geom_density_ridges(stat = "density") + facet_wrap(vars(year))
ggplot(daily, aes(x = sum_sub2, y = month, height = ..density..)) +
  geom_density_ridges(stat = "density") + facet_wrap(vars(year))
ggplot(daily, aes(x = sum_sub3, y = month, height = ..density..)) +
  geom_density_ridges(stat = "density") + facet_wrap(vars(year))
```

#### Hourly
```{r}
hourly <- submeter_data %>% 
  group_by(year = year(datetime),
           month = month(datetime, label = TRUE),
           day = day(datetime),
           hour = hour(datetime)) %>%  
  summarize(sum_sub1 = sum(Sub_metering_1), sum_sub2 = sum(Sub_metering_2), sum_sub3 = sum(Sub_metering_3))
 

######## Plotting starts here#####################
heatmap_sub <- function(data, fill_data = "sum_sub1"){
  if(fill_data == "sum_sub1"){
    title_text <- "In Kitchen"
  }else if(fill_data == "sum_sub2"){
    title_text <- "In Laundry Room"
  }else{
    title_text <- "Water-heater and Air-conditioner"
  }
  
  data %>% 
  ggplot(aes_string("day", "hour", fill = fill_data)) +
  geom_tile(color = "white", size = 0.1) + 
  scale_fill_viridis(name = "Sum of Hourly Watt", option = "C") +
  facet_grid(year ~ month) + 
  scale_y_continuous(trans = "reverse", breaks = unique(data$hour)) +
  scale_x_continuous(breaks = c(1, 10, 20, 31)) + 
  theme_minimal(base_size = 8) + 
  labs(
    title = title_text,
    x = "Day", 
    y = "Hour Commencing"
  ) + 
  theme(legend.position = "bottom",
        plot.title = element_text(size = 14, hjust = 0),
        axis.text.y = element_text(size = 6),
        strip.background = element_rect(colour = "white"),
        axis.ticks = element_blank(),
        axis.text = element_text(size = 7),
        legend.title = element_text(size = 8),
        legend.text = element_text(size = 6)
  ) +
  removeGrid()
}

heatmap_sub(hourly)
heatmap_sub(hourly, "sum_sub2")
heatmap_sub(hourly, "sum_sub3")
```

